name: AutoPkg run

on:
  workflow_dispatch: # manually triggered
    inputs:
      recipe:
        description: Recipe to Run (optional)
        required: false

jobs:
  AutoPkg:
    runs-on: macos-latest
    timeout-minutes: 150 # Keeps your builds from running too long
    env:
      MUNKI_VERSION: 6.3.1
      MUNKI_EXPLICIT_VERSION: 6.3.1.4580
      AUTOPKG_VERSION: 2.7.2
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Install Munki
      uses: joncrain/macos-pkg-install@v1.0
      with:
        pkg_url: https://github.com/munki/munki/releases/download/v${{ env.MUNKI_VERSION }}/munkitools-${{ env.MUNKI_EXPLICIT_VERSION }}.pkg

    - name: Install AutoPkg
      uses: joncrain/macos-pkg-install@v1.0
      with:
        pkg_url: https://github.com/autopkg/autopkg/releases/download/v${{ env.AUTOPKG_VERSION }}/autopkg-${{ env.AUTOPKG_VERSION }}.pkg

    - name: Configure AutoPkg
      run: |
        defaults write com.github.autopkg RECIPE_OVERRIDE_DIRS "$GITHUB_WORKSPACE"/autopkg_src/overrides/
        defaults write com.github.autopkg RECIPE_REPO_DIR "$GITHUB_WORKSPACE"/autopkg_src/repos/
        defaults write com.github.autopkg FAIL_RECIPES_WITHOUT_TRUST_INFO -bool YES
        defaults write com.github.autopkg MUNKI_REPO "$GITHUB_WORKSPACE"
        defaults write com.github.autopkg GITHUB_TOKEN "${{ secrets.GITHUB_TOKEN }}"
        git config --global user.name "runner"
        git config --global user.email "runner@githubactions.local"

    - name: Configure AutoPkg Repos
      run: |
        for repo in $(cat ./autopkg_src/repo_list.txt); do autopkg repo-add "$repo"; done

    - name: Update AutoPkg Repos
      run: autopkg repo-update all

    - name: Run makecatalogs
      run: /usr/local/munki/makecatalogs ./ -s

    - name: Run AutoPkg
      run: |
        pip3 install -r ./autopkg_src/requirements.txt
        python3 ./autopkg_src/autopkg_tools.py -l ./autopkg_src/recipe_list.json
      env:
        RECIPE: ${{ github.event.inputs.recipe }}
        SLACK_WEBHOOK_TOKEN: ${{ secrets.autopkg_slack_token }}
        GH_TOKEN: ${{ secrets.RW_REPO_TOKEN }}
